### ISSUE TITLE
Request for code

### ISSUE THREAD

**Issue by zhaofenqiang** [nitika-verma/FeaStNet#1]
Hi, I am very interested in your paper ["FeaStNet: Feature-Steered Graph Convolutions for 3D Shape Analysis"](https://arxiv.org/abs/1706.05206), and I found this corresponding repository in the paper. 

Could you kindly release the code for us to do some further research on the graph convolutions?
Thank you very much!

**Comment by nitika-verma** [comment]
Hi,

Sorry for the delay. I have uploaded the code.
