### ISSUE TITLE
Performance with vertices re-ordering

### ISSUE THREAD

**Issue by EoAelinr** [nitika-verma/FeaStNet#11]
Hello.

I have used your code to train your model on the FAUST dataset (80/20 training/evaluating) and obtains an accuracy of 0.92 after 175k iterations.
However, if I simply change the order of the vertices in the mesh (and accordingly re-index the faces and adapt the labels), the accuracy from the learned model drops to near 0.

Is that expected behavior, or have I done something wrong ?

My understanding is that the learned weights _Wm_ have no relation to the mesh topology only to its surface, and that the learned weight function _qm_ is only sensitive to the neighbors order, which should not change by simply re-ordering the vertices.

**Comment by xuesanshi** [comment]
I want to ask how to run the code, don't know how to load the data, can you tell me?

**Comment by EoAelinr** [comment]
I just loaded the .ply files from `MPI-FAUST/training/registrations`, computed the adjacent vertices of each vertex, and then fed it to the network (xyz in x, adjacency indexes in adj, and the class of each point in y_). At each iteration the data from one mesh is fed.
Maybe that I am missing something on this side though, since my model seems to fail to generalize to different topologies.

**Comment by EoAelinr** [comment]
As expected I had some error in my code, a typo created an indexing issue during the processing of the adjacency matrix. The created error being relative to the mesh topology (and vertex ordering), it cancelled itself when using only meshes from FAUST.
