### ISSUE TITLE
get_slices

### ISSUE THREAD

**Issue by AndrewLischishin** [nitika-verma/FeaStNet#3]
Hi Nitika,
could you please explain in a bit more details, how exactly get_slices works, especially at the point where gather function is called.  And also, how is adj represented, you say that it is a list of neighbour's indices, but it should be a tensor, and if it a tensor, is it just 0 and 1?
Thanks in advance!
Andrej

**Comment by nitika-verma** [comment]
Hi,

I am very sorry for the late reply.

get_slices takes as an input x (batch_size, num_points, in_channels) and adj (batch_size, num_points, K) and outputs slices (batch_size, num_points, K, in_channels). It gathers the values in x according to the neighborhood indices indicated in adj.

The input adj_input is a list of the indices of the neighbors of the vertices. Let's say the maximum neighborhood size of the graph is 5 and the vertex 1 has neighbors 2,3,4 then the first entry in this list would be 1,2,3,4,0.

Thank you.
