### ISSUE TITLE
Replicate the paper results

### ISSUE THREAD

**Issue by asnt** [nitika-verma/FeaStNet#4]
Thank you for sharing this code.

Could you please explain further how to reproduce the paper results?
1. Do you have some further snippets to run the code?
2. `get_model()` seems to provide a skeleton for the shape segmentation but not the architecture reported in the paper. There should be Lin512-Lin2048-MaxPool before the last two dense layers, right?
3. The output channels are all set to 8, e.g., https://github.com/nitika-verma/FeaStNet/blob/53903d5d5f3e07f38d7aebd94be9f5f5b180c3e0/src/model.py#L208 Shouldn't that be 16, 32, 64..., to reproduce the paper?
4. Can you provide the code for the shape correspondence problem?

Thank you.

Edit: For point 2., I realise now that the provided architecture matches the single scale model.

**Comment by nitika-verma** [comment]
Hi.

Sorry for the late reply.

1. I have updated train.py to add some information on training. The format of the inputs train_data and adj_input are present in the comment in the file.
2. The architecture in the code is the single-scale architecture reported in the paper for the FAUST dataset.
3. Thank you for pointing this out. I corrected it.
4. The dataset for the shape correspondence problem is available http://faust.is.tue.mpg.de/. You will need to sign up here to get it and create/read the files as highlighted in point 2.

Thank you.
