### ISSUE TITLE
Parameters for FAUST dataset

### ISSUE THREAD

**Issue by mathue** [nitika-verma/FeaStNet#6]
Dear Mrs. Verma,
which values do you use for N (according to the paper) or the batch_size (according to the code) in the case of the FAUST dataset?
Will you provide your routines for loading the FAUST data?

Best regards,
Martin.

**Comment by nitika-verma** [comment]
Hi,

N is the number of points in the mesh (6890) and batch size is 1.

The dataset for the shape correspondence problem is available http://faust.is.tue.mpg.de/. You will need to sign up here to get it and create/read the files as highlighted in point 2.

Regards,
Nitika

**Comment by mathue** [comment]
So you fed the whole point cloud at one into the algorithm? That is a nice property which makes your method different from others since it can therefore also be applied to global point cloud/mesh classification tasks.

**Comment by nitika-verma** [comment]
Yes. The whole point cloud/mesh is fed into the algorithm. It can thus be used for the applications you suggested.

Thank you.
