### ISSUE TITLE
Bug in get_slices()

### ISSUE THREAD

**Issue by edgar-tr** [nitika-verma/FeaStNet#7]
Hi Nitika,

there seems to be a bug in get_slices() that causes all elements of the batch (except for the first) to be indexed wrongly.  In src/model.py, line 92 should be `adj_flat = adj_flat*(num_points+1)` instead of `adj_flat = adj_flat*in_channels`.
As a simple test case, use `return tf.stop_gradient(tf.convert_to_tensor([[[1., 0., 0.], [0., 1., 0.], [0., 0., 1.]]]))` for weight_variable, `return tf.stop_gradient(tf.convert_to_tensor([0., 0., 0.]))` for bias_variable, and then use a single conv layer like this: `net = custom_conv2d(net, adjacency, 3, M=1, translation_invariance=False)` (where the vertex features are simply the xyz coordinates). That should be a Laplacian smoothing, but the results looked only correct for the first element of the batch for me. With the change from above, all elements look good.

Regards,
Edgar

**Comment by nitika-verma** [comment]
Hi,

Thank you for pointing this out. Fixed with commit 056bb52.

Closing this now.

Regards,
Nitika
